### ISSUE TITLE
CERIF-XML to CERIF-RDF Converter?

### ISSUE THREAD

**Issue by rogargon** [EuroCRIS/CERIF-RDF#1]
Is there any tool capable of transforming CERIF XML into CERIF RDF using the CERIF ontology?

**Comment by lremy** [comment]
Hi Roberto,
we are actually working on the CERIF RDF expression. It's even not a beta yet as it is not complete (experimental version for now!):)
So we have not designed any tool to go from one expression to the other.

Development branch is going on with this experiment, keep in touch!

Laurent

**Comment by rogargon** [comment]
Thanks Laurent for the update. 
Is this a continuation of previous work building a CERIF Ontology (https://www.eurocris.org/ontology)?

**Comment by lremy** [comment]
Not really Roberto.
Actually we are only experimenting a simple description of the data model using RDF, for documentation mainly. This work is done in parallel with the update of the definition of the entities and properties.
Once it will reach a more-or-less stable state, we may merge it with the CERIF1.3 ontology to get an RDF-usable representation of CERIF.
